Return single max timestamp
doctrine/annotations pull request #105
Opened 2016-11-14 01:42 UTC by trsteel88

This PR fixes an issue where the cache is constantly being written - wasting IO.

After looking into this further, I found that the problem I'm having with excessive IO is because getLastModification is merging the timestamps incorrectly.

The result of the following can't be merged:

```php
dump(array_merge(
    [$filename ? filemtime($filename) : 0],
    array_map([$this, 'getTraitLastModificationTimes'], $class->getTraits()),
    array_map([$this, 'getLastModification'], $class->getInterfaces()),
    $parent ? [$this->getLastModification($parent)] : []
));
```

![screen shot 2016-11-14 at 11 29 03 am](https://cloud.githubusercontent.com/assets/869933/20250868/659c99c2-aa5f-11e6-85ee-e7f8b63e7d1d.png)

The result of this is that it can't work out the max() of the traits.

To resolve this, I updated getTraitLastModificationTimes to always return the max timestamp.

Using this PR in favour of another change I made: https://github.com/doctrine/annotations/pull/104

2016-11-14 10:01 UTC, mikeSimonson commented
@trsteel88 Can you add a test case for this ?

2016-11-14 11:16 UTC, stof commented on lib/Doctrine/Common/Annotations/CachedReader.php
>      private function getTraitLastModificationTimes(ReflectionClass $reflectionTrait)
the name should be changed, as it does not return several times anymore

2016-11-14 11:48 UTC, Ocramius requested changes
A test case demonstrating the current issue is also needed.

2016-11-14 11:48 UTC, Ocramius commented on lib/Doctrine/Common/Annotations/CachedReader.php
>      private function getTraitLastModificationTimes(ReflectionClass $reflectionTrait)
This method returns an `int[]`, which is then passed to `max()` in `private function getLastModification()`. If I get it correctly, the fix is different, and it is to change that function's body instead:

```php
         return max(array_merge(
             [$filename ? filemtime($filename) : 0],
            // notice the three dots:
             ...array_map([$this, 'getTraitLastModificationTimes'], $class->getTraits()),
             array_map([$this, 'getLastModification'], $class->getInterfaces()),
             $parent ? [$this->getLastModification($parent)] : []
         ));
```

2016-11-18 21:32 UTC, trsteel88 commented on lib/Doctrine/Common/Annotations/CachedReader.php
>      private function getTraitLastModificationTimes(ReflectionClass $reflectionTrait)
The three dots don't work.

Compile Error: Cannot use positional argument after argument unpacking

2016-11-18 21:50 UTC, trsteel88 commented
@Ocramius @mikeSimonson where should this test go? I can't see any existing tests for the CachedReacher class.

I'm assuming we just need a single test to ensure that getLastModification returns an int (and never an array)?

2016-11-21 14:02 UTC, mikeSimonson commented
@trsteel88 The test should go [there](https://github.com/doctrine/annotations/blob/master/tests/Doctrine/Tests/Common/Annotations/CachedReaderTest.php) with the other tests of cachedReader.

2016-11-23 05:34 UTC, trsteel88 commented
Thanks @mikeSimonson - I'll add one in.

Also, I noticed that within ***fetchFromCache()*** it has the following:

```
     if (($data = $this->cache->fetch($cacheKey)) !== false) {
            if (!$this->debug || $this->isCacheFresh($cacheKey, $class)) {
                return $data;
            }
        }
```

In dev, debug is always going to be false. This is rendering the cache completely useless. Is this meant to be there?

2016-11-23 05:41 UTC, Ocramius commented
In dev mode, caches should really not be hit at all, so that's intentional.

2016-12-30 15:45 UTC, merged

2016-12-30 15:46 UTC, Ocramius commented
@trsteel88 merged, I added a test to it :-)

`master`: doctrine/annotations@8ac9494a6b91fca4b51a9e845179afc50d25d634
`1.3.x`: doctrine/annotations@bc1963dbceda634ee91c97d0bd19ccd1fc9a0f98

2017-01-10 10:25 UTC, chosroes commented
This caused the error in #117 =/

2017-01-10 11:47 UTC, Ocramius commented
@chosroes I still need a test case for that - can't do anything without it, and I'm not bootstrapping a symfony application for that.