Allow support for JSON arrays within annotations
doctrine/annotations pull request #122
Opened 2017-02-17 10:52 UTC by rlweb

As said, added square brackets to complete support for JSON.

2017-02-17 11:20 UTC, Ocramius requested changes
Code looks good, but we need to improve the testing of nested values, optional additional values.

This should be done both in the parser tests, and in the annotation reader afterwards, in my opinion.

@guilhermeblanco any opinion on supporting this?

2017-02-17 11:20 UTC, Ocramius commented on tests/Doctrine/Tests/Common/Annotations/DocParserTest.php
> +            array('array', '[@AnnotationExtendsAnnotationTargetAll,@AnnotationExtendsAnnotationTargetAll]'),
Would need a few tests around parsing array elements, their order, and different types of sub-elements

2017-02-17 11:20 UTC, Ocramius commented on tests/Doctrine/Tests/Common/Annotations/DocParserTest.php
> +            array('array', '[@AnnotationExtendsAnnotationTargetAll,@AnnotationExtendsAnnotationTargetAll]'),
Also nested arrays

2017-02-17 11:20 UTC, Ocramius commented on lib/Doctrine/Common/Annotations/DocLexer.php
> +    const T_OPEN_SQR_BRACKETS   = 113;
`SQUARE`

2017-02-17 11:20 UTC, Ocramius commented on lib/Doctrine/Common/Annotations/DocLexer.php
> +    const T_CLOSE_SQR_BRACKETS  = 114;
`SQUARE`

2018-10-16 03:57 UTC, Majkl578 commented
This is something that should be relatively easy with the new parser in Annotations 2.0. Milestoning, since there is no relevant issue, but it will require different implementation.

2019-12-04 14:29 UTC, closed without merging